<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Dsh.Preset</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cordis\Cordis.Core\Cordis.Core.csproj" />
    <ProjectReference Include="..\..\Cordis\Cordis.Plugin.Loader\Cordis.Plugin.Loader.csproj" />
    <ProjectReference Include="..\..\Cordis\Cordis.Plugin.Include\Cordis.Plugin.Include.csproj" />
    <ProjectReference Include="..\Dsh.SystemPrompt\Dsh.SystemPrompt.csproj" />
  </ItemGroup>

</Project>
