<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Harness.Schedule</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cordis\Cordis.Core\Cordis.Core.csproj" />
    <ProjectReference Include="..\..\Cordis\Cordis.Plugin.Timer\Cordis.Plugin.Timer.csproj" />
  </ItemGroup>

</Project>
