# Manual build-and-test for the Phase 4 preset + guard capability seams.
#
# `dotnet build`/`dotnet test` are blocked by the host sandbox: MSBuild's Csc task spawns the C#
# compiler with captured stdout/stderr, and the sandbox denies child processes that capture output
# through pipes (the same boundary documented in the harness pwsh tool notes). Restore itself
# works, and the compiler runs fine when spawned with inherited stdio, so this script compiles
# each project directly with csc and runs the zero-dependency console assertion suites. On an
# unrestricted host, `dotnet build` / `dotnet run --project tests\Hsh.Preset.Tests` and
# `tests\Hsh.Guard.Tests` work normally.
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$sdkDir = Get-ChildItem (Join-Path $env:ProgramFiles 'dotnet\sdk') -Directory | Sort-Object { [version]$_.Name } -Descending | Select-Object -First 1
$csc = Join-Path $sdkDir.FullName 'Roslyn\bincore\csc.dll'
$pack = Get-ChildItem (Join-Path $env:ProgramFiles 'dotnet\packs\Microsoft.NETCore.App.Ref') -Directory | Sort-Object { [version]$_.Name } -Descending | Select-Object -First 1
$refDir = Join-Path $pack.FullName 'ref\net10.0'
$bin = Join-Path $root 'bin'
New-Item -ItemType Directory -Force -Path $bin | Out-Null

# The host sandbox remaps reads of C:\Program Files\... made by child processes
# (csc fails with CS2001 on -r: paths under it), so reference assemblies are
# copied into the workspace and referenced from there.
$refsDir = Join-Path $bin 'refs'
New-Item -ItemType Directory -Force -Path $refsDir | Out-Null
Copy-Item (Join-Path $refDir '*.dll') $refsDir -Force
$refsFile = Join-Path $bin 'refs.rsp'
Get-ChildItem $refsDir -Filter '*.dll' | ForEach-Object { "-r:$($_.FullName)" } | Set-Content -LiteralPath $refsFile -Encoding utf8

function Sources([string]$Dir) {
    return @(Get-ChildItem $Dir -Filter '*.cs' | ForEach-Object FullName)
}

# Hsh.AgentLoop's GlobalUsings.cs carries only its Hsh.* usings and relies on MSBuild's
# ImplicitUsings for the System.* block. A generated file (outside every project, so no existing
# project is touched) supplies those to the bare csc invocations; duplicate global usings are
# legal, so appending it to every compile is safe.
$implicitUsings = Join-Path $bin 'implicit-usings.cs'
$usingsLines = @(
    '// Generated by build-and-test-preset-guard.ps1: the System.* global usings MSBuild''s',
    '// ImplicitUsings=enable injects, supplied for bare csc compilation (Hsh.AgentLoop declares',
    '// only its Hsh.* global usings in src).',
    'global using System;',
    'global using System.Collections.Generic;',
    'global using System.IO;',
    'global using System.Linq;',
    'global using System.Net.Http;',
    'global using System.Threading;',
    'global using System.Threading.Tasks;'
)
$usingsLines | Set-Content -LiteralPath $implicitUsings -Encoding utf8

function Invoke-Csc {
    param([string[]]$ExtraArgs, [string[]]$Sources, [string]$Label)
    $all = @($Sources) + @($implicitUsings)
    $arguments = @('exec', $csc, '-noconfig', '-nologo', '-langversion:latest', '-nullable:enable', "@$refsFile") + $ExtraArgs + $all
    Write-Host "== $Label =="
    & dotnet @arguments
    if ($LASTEXITCODE -ne 0) { throw "csc failed for $Label (exit $LASTEXITCODE)" }
}

$core = Sources (Join-Path $root 'src\Cordis\Cordis.Core')
$llm = Sources (Join-Path $root 'src\Hsh\Hsh.Llm')
$session = Sources (Join-Path $root 'src\Hsh\Hsh.Session')
$loader = Sources (Join-Path $root 'src\Cordis\Cordis.Plugin.Loader')
$include = Sources (Join-Path $root 'src\Cordis\Cordis.Plugin.Include')
$tools = Sources (Join-Path $root 'src\Hsh\Hsh.Tools')
$systemPrompt = Sources (Join-Path $root 'src\Hsh\Hsh.SystemPrompt')
$persistence = Sources (Join-Path $root 'src\Hsh\Hsh.Session.Persistence')
$agent = Sources (Join-Path $root 'src\Hsh\Hsh.Agent')
$agentLoop = Sources (Join-Path $root 'src\Hsh\Hsh.AgentLoop')
$preset = Sources (Join-Path $root 'src\Hsh\Hsh.Preset')
$guard = Sources (Join-Path $root 'src\Hsh\Hsh.Guard')
$presetTests = Sources (Join-Path $root 'tests\Hsh.Preset.Tests')
$guardTests = Sources (Join-Path $root 'tests\Hsh.Guard.Tests')

# Compile in dependency order: Cordis.Core -> Hsh.Llm -> Hsh.Session -> Cordis.Plugin.Loader ->
# Cordis.Plugin.Include -> Hsh.Tools -> Hsh.SystemPrompt -> Hsh.Session.Persistence -> Hsh.Agent
# -> Hsh.AgentLoop -> Hsh.Preset -> Hsh.Guard, then both test executables.
$coreDll = Join-Path $bin 'Cordis.Core.dll'
$llmDll = Join-Path $bin 'Hsh.Llm.dll'
$sessionDll = Join-Path $bin 'Hsh.Session.dll'
$loaderDll = Join-Path $bin 'Cordis.Plugin.Loader.dll'
$includeDll = Join-Path $bin 'Cordis.Plugin.Include.dll'
$toolsDll = Join-Path $bin 'Hsh.Tools.dll'
$systemPromptDll = Join-Path $bin 'Hsh.SystemPrompt.dll'
$persistenceDll = Join-Path $bin 'Hsh.Session.Persistence.dll'
$agentDll = Join-Path $bin 'Hsh.Agent.dll'
$agentLoopDll = Join-Path $bin 'Hsh.AgentLoop.dll'
$presetDll = Join-Path $bin 'Hsh.Preset.dll'
$guardDll = Join-Path $bin 'Hsh.Guard.dll'
$presetTestsDll = Join-Path $bin 'Hsh.Preset.Tests.dll'
$guardTestsDll = Join-Path $bin 'Hsh.Guard.Tests.dll'

Invoke-Csc -ExtraArgs @('-target:library', "-out:$coreDll") -Sources $core -Label 'Cordis.Core'
Invoke-Csc -ExtraArgs @('-target:library', "-out:$llmDll", "-r:$coreDll") -Sources $llm -Label 'Hsh.Llm'
Invoke-Csc -ExtraArgs @('-target:library', "-out:$sessionDll", "-r:$coreDll", "-r:$llmDll") -Sources $session -Label 'Hsh.Session'
Invoke-Csc -ExtraArgs @('-target:library', "-out:$loaderDll", "-r:$coreDll") -Sources $loader -Label 'Cordis.Plugin.Loader'
Invoke-Csc -ExtraArgs @('-target:library', "-out:$includeDll", "-r:$coreDll", "-r:$loaderDll") -Sources $include -Label 'Cordis.Plugin.Include'
Invoke-Csc -ExtraArgs @('-target:library', "-out:$toolsDll", "-r:$coreDll", "-r:$sessionDll", "-r:$llmDll") -Sources $tools -Label 'Hsh.Tools'
Invoke-Csc -ExtraArgs @('-target:library', "-out:$systemPromptDll", "-r:$coreDll", "-r:$llmDll", "-r:$toolsDll") -Sources $systemPrompt -Label 'Hsh.SystemPrompt'
Invoke-Csc -ExtraArgs @('-target:library', "-out:$persistenceDll", "-r:$coreDll", "-r:$sessionDll", "-r:$llmDll") -Sources $persistence -Label 'Hsh.Session.Persistence'
Invoke-Csc -ExtraArgs @('-target:library', "-out:$agentDll", "-r:$coreDll", "-r:$sessionDll", "-r:$llmDll") -Sources $agent -Label 'Hsh.Agent'
Invoke-Csc -ExtraArgs @('-target:library', "-out:$agentLoopDll", "-r:$coreDll", "-r:$agentDll", "-r:$llmDll", "-r:$sessionDll", "-r:$persistenceDll", "-r:$systemPromptDll", "-r:$toolsDll") -Sources $agentLoop -Label 'Hsh.AgentLoop'
Invoke-Csc -ExtraArgs @('-target:library', "-out:$presetDll", "-r:$coreDll", "-r:$loaderDll", "-r:$includeDll", "-r:$systemPromptDll") -Sources $preset -Label 'Hsh.Preset'
Invoke-Csc -ExtraArgs @('-target:library', "-out:$guardDll", "-r:$coreDll", "-r:$llmDll", "-r:$sessionDll", "-r:$toolsDll") -Sources $guard -Label 'Hsh.Guard'
Invoke-Csc -ExtraArgs @('-target:exe', "-out:$presetTestsDll", "-r:$coreDll", "-r:$loaderDll", "-r:$includeDll", "-r:$systemPromptDll", "-r:$presetDll") -Sources $presetTests -Label 'Hsh.Preset.Tests'
Invoke-Csc -ExtraArgs @('-target:exe', "-out:$guardTestsDll", "-r:$coreDll", "-r:$agentDll", "-r:$agentLoopDll", "-r:$guardDll", "-r:$llmDll", "-r:$sessionDll", "-r:$persistenceDll", "-r:$systemPromptDll", "-r:$toolsDll") -Sources $guardTests -Label 'Hsh.Guard.Tests'

$runtime = $pack.Name
$runtimeConfig = @{
    runtimeOptions = @{
        tfm = 'net10.0'
        framework = @{ name = 'Microsoft.NETCore.App'; version = $runtime }
        rollForward = 'LatestMinor'
        configProperties = @{ 'System.Reflection.Metadata.MetadataUpdater.IsSupported' = $false }
    }
}
$runtimeConfig | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath (Join-Path $bin 'Hsh.Preset.Tests.runtimeconfig.json') -Encoding utf8
$runtimeConfig | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath (Join-Path $bin 'Hsh.Guard.Tests.runtimeconfig.json') -Encoding utf8

Write-Host '== Running Hsh.Preset.Tests =='
& dotnet $presetTestsDll
if ($LASTEXITCODE -ne 0) { throw "Hsh.Preset.Tests failed (exit $LASTEXITCODE)" }

Write-Host '== Running Hsh.Guard.Tests =='
& dotnet $guardTestsDll
if ($LASTEXITCODE -ne 0) { throw "Hsh.Guard.Tests failed (exit $LASTEXITCODE)" }

exit 0
