<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Harness.Workspace.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Cordis\Cordis.Core\Cordis.Core.csproj" />
    <ProjectReference Include="..\..\src\Hsh\Hsh.Workspace\Hsh.Workspace.csproj" />
    <ProjectReference Include="..\..\src\Hsh\Hsh.Storage\Hsh.Storage.csproj" />
  </ItemGroup>

</Project>
