<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Harness.Cordis.Schemastery</RootNamespace>
    <AssemblyName>Cordis.Schemastery</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cordis.Cosmokit\Cordis.Cosmokit.csproj" />
  </ItemGroup>

</Project>
